import './js/fetchbooks/main-section';
import './js/category';
import './js/mobile-menu';
import './js/theme-switch';
import './js/open-close';
import './js/anchor-btn';
import './js/about-book-modal';
import './js/modals';
import './js/slider-set.js';
